# Generated by Django 5.2.7 on 2025-10-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer_email",
        ),
        migrations.AddField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
