# Generated by Django 4.2.16 on 2025-12-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_payment_paymentmethod_paymentcallback_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="name",
            field=models.CharField(default="Cash on Delivery", max_length=50),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="provider",
            field=models.CharField(
                choices=[("cash", "Cash on Delivery")], default="cash", max_length=50
            ),
        ),
    ]
