# Generated by Django 4.2.16 on 2025-12-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_paymentmethod_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="Nabweru near playground, Wakiso, Uganda",
                        max_length=300,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="0200 901 914, +256 783 238 522", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="clericdesigns@gmail.com", max_length=254
                    ),
                ),
                (
                    "business_hours",
                    models.CharField(
                        default="Monday - Friday: 07:00 AM - 10:00 PM, Saturday & Sunday: 8:00 AM - 10:00 PM",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "graphic_design_description",
                    models.TextField(
                        default="Professional graphic design services for all your branding and marketing needs."
                    ),
                ),
                (
                    "printing_description",
                    models.TextField(
                        default="High-quality printing services for all your documents and marketing materials."
                    ),
                ),
                (
                    "electronics_description",
                    models.TextField(
                        default="Quality electronics and accessories for all your technology needs."
                    ),
                ),
                (
                    "stationery_description",
                    models.TextField(
                        default="Complete stationery solutions for offices, schools, and personal use."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebsiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "welcome_title",
                    models.CharField(
                        default="Welcome to Stationery World Uganda", max_length=200
                    ),
                ),
                (
                    "welcome_description",
                    models.TextField(
                        default="Your trusted partner in Stationery, Electronics, Phone Accessories, Graphic Designing & Printing"
                    ),
                ),
                (
                    "company_description",
                    models.TextField(
                        default="We provide quality stationery, electronics, and printing services to individuals and businesses across Uganda."
                    ),
                ),
            ],
        ),
    ]
