# Generated by Django 4.2.16 on 2025-12-02 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_contactinfo_serviceinfo_websitecontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceInfoLegacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "graphic_design_description",
                    models.TextField(
                        default="Professional graphic design services for all your branding and marketing needs."
                    ),
                ),
                (
                    "printing_description",
                    models.TextField(
                        default="High-quality printing services for all your documents and marketing materials."
                    ),
                ),
                (
                    "electronics_description",
                    models.TextField(
                        default="Quality electronics and accessories for all your technology needs."
                    ),
                ),
                (
                    "stationery_description",
                    models.TextField(
                        default="Complete stationery solutions for offices, schools, and personal use."
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="serviceinfo",
            options={"ordering": ["display_order", "name"]},
        ),
        migrations.RemoveField(
            model_name="serviceinfo",
            name="electronics_description",
        ),
        migrations.RemoveField(
            model_name="serviceinfo",
            name="graphic_design_description",
        ),
        migrations.RemoveField(
            model_name="serviceinfo",
            name="printing_description",
        ),
        migrations.RemoveField(
            model_name="serviceinfo",
            name="stationery_description",
        ),
        migrations.AddField(
            model_name="serviceinfo",
            name="description",
            field=models.TextField(default="Service description"),
        ),
        migrations.AddField(
            model_name="serviceinfo",
            name="display_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="serviceinfo",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="serviceinfo",
            name="name",
            field=models.CharField(
                choices=[
                    ("graphic_design", "Graphic Design"),
                    ("printing", "Printing & Photocopying"),
                    ("electronics", "Electronics"),
                    ("stationery", "Stationery Supply"),
                ],
                default="graphic_design",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="serviceinfo",
            name="title",
            field=models.CharField(default="Service Title", max_length=200),
        ),
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="services/")),
                ("caption", models.CharField(blank=True, max_length=200, null=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.serviceinfo",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
    ]
