# Generated by Django 4.2.16 on 2025-12-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_serviceinfolegacy_alter_serviceinfo_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="priority",
            field=models.IntegerField(
                default=0, help_text="Higher priority products appear first"
            ),
        ),
    ]
